"""
Import Project Management and Activity Log data from Excel into PostgreSQL SQL.
Source: Sales_Management_Tomas Tech_20260404_R1.xlsx
"""
import pandas as pd
import warnings
import re

warnings.filterwarnings('ignore')

EXCEL_PATH = r'C:\Users\R.Nozaki\Downloads\Sales_Management_Tomas Tech_20260404_R1.xlsx'
OUTPUT_PATH = r'C:\Users\R.Nozaki\Downloads\Pegasus_ERP_R1\database\import_deals_activities.sql'

xlsx = pd.ExcelFile(EXCEL_PATH)

# Read sheets
df_pm = pd.read_excel(xlsx, sheet_name='Project Management', header=2)
df_pm = df_pm.dropna(subset=['Deal No.'])

df_al = pd.read_excel(xlsx, sheet_name='Activity Log', header=2)
df_al = df_al.dropna(subset=['Date'])


def esc(val):
    """Escape string for SQL"""
    if pd.isna(val):
        return 'NULL'
    s = str(val).strip()
    if not s:
        return 'NULL'
    s = s.replace("'", "''")
    return f"'{s}'"


def esc_date(val):
    """Format date for SQL"""
    if pd.isna(val):
        return 'NULL'
    try:
        return f"'{pd.Timestamp(val).strftime('%Y-%m-%d')}'"
    except:
        return 'NULL'


def esc_num(val, multiplier=1):
    """Format number for SQL"""
    if pd.isna(val):
        return '0'
    try:
        v = float(val) * multiplier
        if v == int(v):
            return str(int(v))
        return f'{v:.2f}'
    except:
        return '0'


# Status mapping: Excel status -> deal_statuses.status_name
# The deal_statuses were updated in schema_crm_v2.sql with these names:
# ① Appointment(10%), ② 1st Meeting(20%), ③ Proposal(30%), ④ Quotation(40%),
# ⑤ Negotiation(50%), ⑥ Final Review(60%), ⑦ Contract(80%), ⑧ Closed Won(100%),
# ⑨ Closed Lost(0%), ⑩ On Hold(0%)
STATUS_MAP = {
    '① Appointment': '① Appointment',
    '② 1st Meeting': '② 1st Meeting',
    '③ Proposal': '③ Proposal',
    '④ Quotation': '④ Quotation',
    '⑤ Negotiation': '⑤ Negotiation',
}

# Activity type mapping: Excel -> activity_categories.category_name
# Updated in schema_crm_v2.sql: Call, Walk-in Visit, Posting, Referral,
# Meeting Follow-up, Email/LINE, Exhibition, Other, Meeting
ACTIVITY_MAP = {
    'Call (Phone)': 'Call (Phone)',
    'Walk-in Visit': 'Walk-in Visit',
    'Email / LINE Contact': 'Email / LINE Contact',
    'Meeting': 'Meeting',
    'Other': 'Other',
}

lines = []
lines.append("-- ============================================================")
lines.append("-- PEGASUS ERP: Import Deals & Activities from Excel")
lines.append("-- Source: Sales_Management_Tomas Tech_20260404_R1.xlsx")
lines.append("-- Generated by import_deals_activities.py")
lines.append("-- ============================================================")
lines.append("")

# ── 1. Ensure customers exist for PM companies ──
lines.append("-- === Ensure customers exist (PM + AL companies) ===")
all_companies = set()
for _, r in df_pm.iterrows():
    c = str(r['Company Name']).strip() if pd.notna(r['Company Name']) else ''
    if c:
        all_companies.add(c)
for _, r in df_al.iterrows():
    c = str(r['Company Name']).strip() if pd.notna(r['Company Name']) else ''
    if c:
        all_companies.add(c)

for i, comp in enumerate(sorted(all_companies), start=1):
    comp_esc = comp.replace("'", "''")
    code = f'CRM-{i:04d}'
    lines.append(
        f"INSERT INTO customers (customer_name, customer_code, division_id, is_deleted) "
        f"SELECT '{comp_esc}', '{code}', 1, FALSE "
        f"WHERE NOT EXISTS (SELECT 1 FROM customers WHERE customer_name = '{comp_esc}');"
    )
lines.append("")

# ── 2. Insert Deals from Project Management ──
lines.append("-- === Insert Deals (Project Management sheet, 22 rows) ===")
for idx, r in df_pm.iterrows():
    deal_no = str(r['Deal No.']).strip()
    deal_name = r['Deal Name /\nProject Name'] if pd.notna(r['Deal Name /\nProject Name']) else ''
    company = str(r['Company Name']).strip() if pd.notna(r['Company Name']) else ''
    contact = str(r['Contact Name']).strip() if pd.notna(r['Contact Name']) else ''
    sales_person = str(r['Sales Person']).strip() if pd.notna(r['Sales Person']) else ''
    solution = str(r['Solution Category']).strip() if pd.notna(r['Solution Category']) else ''
    status_raw = str(r['Status']).strip() if pd.notna(r['Status']) else ''
    budget_status = str(r['Budget\nStatus']).strip() if pd.notna(r['Budget\nStatus']) else 'No'
    next_action = r['Next Action'] if pd.notna(r['Next Action']) else ''
    meeting_notes = r['Meeting Notes'] if pd.notna(r['Meeting Notes']) else ''

    first_contact = esc_date(r['First Contact Date'])
    expected_order = esc_date(r['Expected Order Date'])
    due_date = esc_date(r['Due Date'])

    budget_amount = esc_num(r['Budget Amount\n(10k THB)'], 10000)
    win_rate = esc_num(r['Win Rate (%)'])
    est_revenue = esc_num(r['Est. Revenue\n(10k THB)'], 10000)
    est_profit = esc_num(r['Est. Profit\n(10k THB)'], 10000)
    eval_profit = esc_num(r['Eval. Profit\n(10k THB)'], 10000)

    # Map status
    status_name = STATUS_MAP.get(status_raw, status_raw)

    lines.append(f"-- Deal: {deal_no}")
    lines.append(
        f"INSERT INTO deals (deal_no, deal_name, customer_id, customer_staff, "
        f"sales_person_name, solution_category_id, status_id, "
        f"first_contact_date, expected_close, budget_status, budget_amount, "
        f"win_rate, est_revenue, est_profit, eval_profit, "
        f"next_action, due_date, meeting_notes, "
        f"expected_amount, is_deleted, created_by, updated_by) "
        f"VALUES ("
        f"{esc(deal_no)}, {esc(deal_name)}, "
        f"(SELECT customer_id FROM customers WHERE customer_name = {esc(company)} LIMIT 1), "
        f"{esc(contact)}, {esc(sales_person)}, "
        f"(SELECT category_id FROM solution_categories WHERE category_name = {esc(solution)} LIMIT 1), "
        f"(SELECT status_id FROM deal_statuses WHERE status_name = {esc(status_name)} LIMIT 1), "
        f"{first_contact}, {expected_order}, {esc(budget_status)}, {budget_amount}, "
        f"{win_rate}, {est_revenue}, {est_profit}, {eval_profit}, "
        f"{esc(next_action)}, {due_date}, {esc(meeting_notes)}, "
        f"{est_revenue}, FALSE, 1, 1);"
    )

lines.append("")
lines.append("")

# ── 3. Insert Activities from Activity Log ──
lines.append("-- === Insert Activities (Activity Log sheet, 16 rows) ===")
for idx, r in df_al.iterrows():
    act_date = esc_date(r['Date'])
    sales_person = str(r['Sales Person']).strip() if pd.notna(r['Sales Person']) else ''
    action_type_raw = str(r['Action Type']).strip() if pd.notna(r['Action Type']) else ''
    company = str(r['Company Name']).strip() if pd.notna(r['Company Name']) else ''
    contact = str(r['Contact Name']).strip() if pd.notna(r['Contact Name']) else ''
    comment = str(r['Action / Comment']).strip() if pd.notna(r['Action / Comment']) else ''
    next_action = str(r['Next Action']).strip() if pd.notna(r['Next Action']) else ''
    due_date = esc_date(r['Due Date'])

    # Map activity type
    action_type = ACTIVITY_MAP.get(action_type_raw, action_type_raw)

    lines.append(
        f"INSERT INTO deal_activities (deal_id, activity_category_id, activity_date, "
        f"subject, description, contact_person, "
        f"next_action, next_action_date, "
        f"customer_id, company_name, sales_person_name, created_by) "
        f"VALUES ("
        f"NULL, "
        f"(SELECT category_id FROM activity_categories WHERE category_name = {esc(action_type)} LIMIT 1), "
        f"{act_date}, "
        f"{esc(comment)}, "
        f"{esc(comment)}, "
        f"{esc(contact)}, "
        f"{esc(next_action)}, {due_date}, "
        f"(SELECT customer_id FROM customers WHERE customer_name = {esc(company)} LIMIT 1), "
        f"{esc(company)}, {esc(sales_person)}, 1);"
    )

lines.append("")
lines.append("-- Done.")

sql = '\n'.join(lines)
with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
    f.write(sql)

print(f"Generated {OUTPUT_PATH}")
print(f"  Deals:      {len(df_pm)} rows")
print(f"  Activities:  {len(df_al)} rows")
print(f"  Companies:   {len(all_companies)} unique")
print(f"  SQL lines:   {len(lines)}")
